import { Center, Spinner } from "@chakra-ui/react";
import { GetServerSideProps } from "next";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cadastro de Videos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Center h="100vh">
        <Spinner size="xl" />
      </Center>
    </div>
  );
}
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = ctx.req.cookies;

  if (!session.authenticated) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  } else {
    return {
      redirect: {
        destination: "/home",
        permanent: false,
      },
    };
  }
};
